### ISSUE TITLE
onnx转化

### ISSUE THREAD

**Issue by shuaizenge** [AXERA-TECH/ax-models#20]
尝试用文件中的pp_human_seg_mobile_sim.onnx转化为joint文件，失败，log如下：

```
[W Context.cpp:69] Warning: torch.set_deterministic is in beta, and its design and  functionality may change in the future. (function operator())
[19 14:30:37 <frozen super_pulsar.proto.configuration_super_pulsar_manip>:38] WRN migrate all stand-alone args into a single task
[19 14:30:37 <frozen super_pulsar.proto.configuration_super_pulsar_manip>:156] set task task_0's 0th input model path as /data/model/pp_seg_model.onnx
[19 14:30:37 <frozen super_pulsar.proto.configuration_super_pulsar_manip>:175] set task task_0's 0th output model path as /data/model/pp_seg_model.joint
[19 14:30:37 <frozen super_pulsar.proto.configuration_super_pulsar_manip>:294] set task task_0's pulsar_conf.output_dir as /data
/opt/venv/lib/python3.6/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  /pytorch/c10/cuda/CUDAFunctions.cpp:100.)
  return torch._C._cuda_getDeviceCount() > 0
[19 14:30:38 <frozen super_pulsar.func_wrappers.wrapper_pulsar_build>:17] planning task task_0
[19 14:30:38 <frozen super_pulsar.func_wrappers.pulsar_build.neuwizard_step>:459] WRN affine_preprocess at QAT model compiling is deprecated, insert enforce_integers at front, please use scale_to_integers instead.
[19 14:30:38 <frozen super_pulsar.func_wrappers.wrapper_pulsar_build>:340] ################## Running task task_0 ##################
[19 14:30:38 <frozen super_pulsar.toolchain_wrappers.wrapper_neuwizard>:30] python3 /root/python_modules/super_pulsar/super_pulsar/toolchain_wrappers/wrapper_neuwizard.py --config /tmp/tmpnfrsezzn.prototxt
[19 14:30:39 <frozen super_pulsar.toolchain_wrappers.wrapper_neuwizard>:36] DBG [neuwizard] [W Context.cpp:69] Warning: torch.set_deterministic is in beta, and its design and  functionality may change in the future. (function operator())
[19 14:30:40 <frozen super_pulsar.toolchain_wrappers.wrapper_neuwizard>:36] DBG [neuwizard] /opt/venv/lib/python3.6/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  /pytorch/c10/cuda/CUDAFunctions.cpp:100.)
[19 14:30:40 <frozen super_pulsar.toolchain_wrappers.wrapper_neuwizard>:36] DBG [neuwizard] return torch._C._cuda_getDeviceCount() > 0
[19 14:30:40 <frozen super_pulsar.toolchain_wrappers.wrapper_neuwizard>:36] DBG [neuwizard] ONNX Model Version 11 for "/data/model/pp_seg_model.onnx"
[19 14:30:40 <frozen super_pulsar.toolchain_wrappers.wrapper_neuwizard>:36] DBG [neuwizard] validate onnx failed: Field 'type' of value_info is required but missing.
[19 14:30:40 <frozen super_pulsar.toolchain_wrappers.wrapper_neuwizard>:36] DBG [neuwizard] Planning load step finished; elapsed time: 0.00s
[19 14:30:40 <frozen super_pulsar.toolchain_wrappers.wrapper_neuwizard>:36] DBG [neuwizard] Planning transform step finished; elapsed time: 0.06s
[19 14:30:40 <frozen super_pulsar.toolchain_wrappers.wrapper_neuwizard>:36] DBG [neuwizard] Planning transform step finished; elapsed time: 0.00s
[19 14:30:40 <frozen super_pulsar.toolchain_wrappers.wrapper_neuwizard>:36] DBG [neuwizard] Planning transform step finished; elapsed time: 0.00s
[19 14:30:40 <frozen super_pulsar.toolchain_wrappers.wrapper_neuwizard>:36] DBG [neuwizard] Traceback (most recent call last):
[19 14:30:40 <frozen super_pulsar.toolchain_wrappers.wrapper_neuwizard>:36] DBG [neuwizard] File "</root/python_modules/super_pulsar/super_pulsar/toolchain_wrappers/wrapper_neuwizard.py>", line 3, in <module>**
[19 14:30:40 <frozen super_pulsar.toolchain_wrappers.wrapper_neuwizard>:36] DBG [neuwizard] File "<frozen super_pulsar.toolchain_wrappers.wrapper_neuwizard>", line 95, in <module>
[19 14:30:40 <frozen super_pulsar.toolchain_wrappers.wrapper_neuwizard>:36] DBG [neuwizard] File "<frozen super_pulsar.toolchain_wrappers.wrapper_neuwizard>", line 52, in convert
[19 14:30:40 <frozen super_pulsar.toolchain_wrappers.wrapper_neuwizard>:36] DBG [neuwizard] File "<frozen data>", line 237, in scheduler
[19 14:30:40 <frozen super_pulsar.toolchain_wrappers.wrapper_neuwizard>:36] DBG [neuwizard] File "<frozen configuration.parser>", line 62, in get_dataset_loader
[19 14:30:40 <frozen super_pulsar.toolchain_wrappers.wrapper_neuwizard>:36] DBG [neuwizard] File "<frozen dataset.tar_dataset>", line 119, in get_tar_dataset
[19 14:30:40 <frozen super_pulsar.toolchain_wrappers.wrapper_neuwizard>:36] DBG [neuwizard] File "<frozen dataset.tar_dataset>", line 50, in __init__
[19 14:30:40 <frozen super_pulsar.toolchain_wrappers.wrapper_neuwizard>:36] DBG [neuwizard] AssertionError: /data/config/dataset/visdrone_1000
Traceback (most recent call last):
  File "/root/python_modules/super_pulsar/pulsar", line 27, in <module>
    main()
  File "/root/python_modules/super_pulsar/pulsar", line 21, in main
    args.func(args)
  File "<frozen super_pulsar.func_wrappers.wrapper_pulsar_build>", line 410, in <lambda>
  File "<frozen super_pulsar.func_wrappers.wrapper_pulsar_build>", line 343, in main_build
  File "<frozen super_pulsar.func_wrappers.pulsar_build.neuwizard_step>", line 546, in run
  File "<frozen super_pulsar.toolchain_wrappers.wrapper_joint>", line 478, in joint_inject_qvalue
  File "/usr/local/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "<frozen super_pulsar.toolchain_wrappers.wrapper_joint>", line 430, in inplace_joint_manipulator
  File "<frozen super_pulsar.toolchain_wrappers.wrapper_joint>", line 235, in __init__
  File "/usr/local/lib/python3.6/tarfile.py", line 1571, in open
    return func(name, "r", fileobj, **kwargs)
  File "/usr/local/lib/python3.6/tarfile.py", line 1636, in gzopen
    fileobj = gzip.GzipFile(name, mode + "b", compresslevel, fileobj)
  File "/usr/local/lib/python3.6/gzip.py", line 163, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/data/model/model.lava_joint'
```
希望作者能给出pp_human_seg_mobile_sim的prototxt文件和量化数据集来参考

**Comment by ddasdadas** [comment]
同问

**Comment by luduihang** [comment]
同问
